name: webfeed
version: 0.4.6
description: webfeed is a dart package for parsing RSS and Atom feeds. Media & DublinCore namespaces are also supported.
author: Wito Chandra <wito.c.91@gmail.com>
homepage: https://github.com/witochandra/webfeed
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  xml: ^6.0.1
dev_dependencies:
  test: ^1.17.11
  http: ^0.13.3
